# Needleman-Wunch Algorithm

 Marisha Salsabila       16/394091/PA/17182

import library yang diperlukan

In [1]:
import numpy as np
import pandas as pd

menginputkan data blosum score yang didapatkan dari data blosum62 sebagai nilai score yang akan digunakan

In [2]:
blosum = pd.read_csv('blosum62.csv')

In [3]:
blosum

A  R  N  D  C  Q  E  G  H  I ...  P  S  T   W  Y  V  B  Z  X  *
A  4 -1 -2 -2  0 -1 -1  0 -2 -1 ... -1  1  0  -3 -2  0 -2 -1  0 -4
R -1  5  0 -2 -3  1  0 -2  0 -3 ... -2 -1 -1  -3 -2 -3 -1  0 -1 -4
N -2  0  6  1 -3  0  0  0  1 -3 ... -2  1  0  -4 -2 -3  3  0 -1 -4
D -2 -2  1  6 -3  0  2 -1 -1 -3 ... -1  0 -1  -4 -3 -3  4  1 -1 -4
C  0 -3 -3 -3  9 -3 -4 -3 -3 -1 ... -3 -1 -1  -2 -2 -1 -3 -3 -2 -4
Q -1  1  0  0 -3  5  2 -2  0 -3 ... -1  0 -1  -2 -1 -2  0  3 -1 -4
E -1  0  0  2 -4  2  5 -2  0 -3 ... -1  0 -1  -3 -2 -2  1  4 -1 -4
G  0 -2  0 -1 -3 -2 -2  6 -2 -4 ... -2  0 -2  -2 -3 -3 -1 -2 -1 -4
H -2  0  1 -1 -3  0  0 -2  8 -3 ... -2 -1 -2  -2  2 -3  0  0 -1 -4
I -1 -3 -3 -3 -1 -3 -3 -4 -3  4 ... -3 -2 -1  -3 -1  3 -3 -3 -1 -4
L -1 -2 -3 -4 -1 -2 -3 -4 -3  2 ... -3 -2 -1  -2 -1  1 -4 -3 -1 -4
K -1  2  0 -1 -3  1  1 -2 -1 -3 ... -1  0 -1  -3 -2 -2  0  1 -1 -4
M -1 -1 -2 -3 -1  0 -2 -3 -2  1 ... -2 -1 -1  -1 -1  1 -3 -1 -1 -4
F -2 -3 -3 -3 -2 -3 -3 -3 -1  0 ... -4 -2 -2   1  3 -1 -3 -3 -1 -4
P -1 -2 -2 -1 -3 -1 -1 -2 -2 -3 ...  7 -1 -1  -4 -3 -2 -2 -1 -2 -4
S  1 -1  1  0 -1  0  0  0 -1 -2 ... -1  4  1  -3 -2 -2  0  0  0 -4
T  0 -1  0 -1 -1 -1 -1 -2 -2 -1 ... -1  1  5  -2 -2  0 -1 -1  0 -4
W -3 -3 -4 -4 -2 -2 -3 -2 -2 -3 ... -4 -3 -2  11  2 -3 -4 -3 -2 -4
Y -2 -2 -2 -3 -2 -1 -2 -3  2 -1 ... -3 -2 -2   2  7 -1 -3 -2 -1 -4
V  0 -3 -3 -3 -1 -2 -2 -3 -3  3 ... -2 -2  0  -3 -1  4 -3 -2 -1 -4
B -2 -1  3  4 -3  0  1 -1  0 -3 ... -2  0 -1  -4 -3 -3  4  1 -1 -4
Z -1  0  0  1 -3  3  4 -2  0 -3 ... -1  0 -1  -3 -2 -2  1  4 -1 -4
X  0 -1 -1 -1 -2 -1 -1 -1 -1 -1 ... -2  0  0  -2 -1 -1 -1 -1 -1 -4
* -4 -4 -4 -4 -4 -4 -4 -4 -4 -4 ... -4 -4 -4  -4 -4 -4 -4 -4 -4  1

[24 rows x 24 columns]

Menginputkan data sequence protein yang akan diimplementasikan. Pada kasus ini diberikan sequence protein1 = MNALQM dan protein2 = NALMSQA yang kemudian akan digunakan sebagai data sequence dalam algoritma needleman-wunsch untuk dilakukan sequence alignment

In [0]:
protein1 = 'MNALQM'
protein2 = 'NALMSQA'

column = len(protein1)+1
row = len(protein2)+1

In [5]:
print(column)
print(row)

7
8


Membuat sebuah matriks berukuran sepanjang karakter sequence protein1 x panjang karakter sequence protein2

In [0]:
matriks = np.zeros(shape=(row, column), dtype=np.int)

In [7]:
matriks

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

Menginputkan nilai gap pada kolom baris [0][0]

Digunakan nilai gap sebesar = -6

In [0]:
a=0
for i in range (1, row):
    a=a-6
    matriks[i][0]=a
    
b=0
for i in range (1, column):
    b=b-6
    matriks[0][i]=b
    

In [9]:
matriks

array([[  0,  -6, -12, -18, -24, -30, -36],
       [ -6,   0,   0,   0,   0,   0,   0],
       [-12,   0,   0,   0,   0,   0,   0],
       [-18,   0,   0,   0,   0,   0,   0],
       [-24,   0,   0,   0,   0,   0,   0],
       [-30,   0,   0,   0,   0,   0,   0],
       [-36,   0,   0,   0,   0,   0,   0],
       [-42,   0,   0,   0,   0,   0,   0]])

# Scoring Matrix berdasarkan Blosum62 Score

Menginputkan nilai blosum score dari masing-masing pairing karakter dalam sequence

In [0]:
for i in range (1,row):
  for j in range (1,column):
    matriks[i][j]=blosum[protein1[j-1]][protein2[i-1]]

In [11]:
matriks

array([[  0,  -6, -12, -18, -24, -30, -36],
       [ -6,  -2,   6,  -2,  -3,   0,  -2],
       [-12,  -1,  -2,   4,  -1,  -1,  -1],
       [-18,   2,  -3,  -1,   4,  -2,   2],
       [-24,   5,  -2,  -1,   2,   0,   5],
       [-30,  -1,   1,   1,  -2,   0,  -1],
       [-36,   0,   0,  -1,  -2,   5,   0],
       [-42,  -1,  -2,   4,  -1,  -1,  -1]])

dibuat sebuah matriks dengan nama 'matriks_coba' yang akan memuat score dari hasil scoring tiap kolom dan baris berdasarkan aturan dari algoritma needleman-wunsch. Setiap field diisikan oleh nilai maksimum dari perhitungan nilai yang didapatkan dari arah diagonal, vertikal atau horizontal

asal nilai maksimum yang diperoleh dari setiap kolom maupun baris (setiap fieldnya) disimpan dalam matriks arah untuk mempermudah visualisasi penanda arah setiap kolom dan baris.

In [0]:
matriks_coba=matriks
arah = np.full(shape=(row,column), fill_value=" ", dtype=np.str)

# Scoring Matrix Needleman-Wunsch Algorithm

In [0]:
for i in range (1, row):
    arah[i][0]=protein2[i-1]

for i in range (1, column):
    arah[0][i]=protein1[i-1]

gap=6
for i in range (1,row):
  for j in range (1,column):
    Diagonal=matriks[i-1][j-1] + blosum[protein1[j-1]][protein2[i-1]]
    Horizontal=matriks[i][j-1] - gap
    Vertikal=matriks[i-1][j] - gap
    matriks_coba[i][j]=max(Diagonal,Horizontal,Vertikal)
    if matriks_coba[i][j]==Diagonal:
        arah[i][j]='/'
    elif matriks_coba[i][j]==Horizontal:
        arah[i][j]='-'
    elif matriks_coba[i][j]==Vertikal:
        arah[i][j]='|'
    
    

In [14]:
matriks_coba

array([[  0,  -6, -12, -18, -24, -30, -36],
       [ -6,  -2,   0,  -6, -12, -18, -24],
       [-12,  -7,  -4,   4,  -2,  -8, -14],
       [-18, -10, -10,  -2,   8,   2,  -4],
       [-24, -13, -12,  -8,   2,   8,   7],
       [-30, -19, -12, -11,  -4,   2,   7],
       [-36, -25, -18, -13, -10,   1,   2],
       [-42, -31, -24, -14, -14,  -5,   0]])

In [42]:
arah

array([[' ', 'M', 'N', 'A', 'L', 'Q', 'M'],
       ['N', '/', '/', '-', '-', '-', '-'],
       ['A', '/', '/', '/', '-', '-', '-'],
       ['L', '/', '/', '|', '/', '-', '-'],
       ['M', '/', '/', '|', '|', '/', '/'],
       ['S', '|', '/', '/', '|', '/', '/'],
       ['Q', '|', '|', '/', '|', '/', '/'],
       ['A', '|', '|', '/', '/', '|', '/']], dtype='|S1')

In [43]:
arah.shape

(8, 7)

variabel protein_1 dan protein_2 digunakan untuk menampung hasil alignment yang didapatkan dengan melakukan tracking back pada matriks arah yang telah didapatkan sebelumnya

Tracking back dilakukan dengan cara melakukan dari kolom dan baris terakhir pada matriks arah lalu ditelusuri hingga berhasil mencapai baris pertama. Penelusuran dilakukan berdasarkan arah nilai dari setiap field yang telah didapatkan sebelumnya.

# Traceback

In [0]:
protein_1 = protein_2 = ""

i=column-1
j=row-1

while i>=0 and j>=0:
    
      
    if arah[j][i] == '/':
        protein_1 = protein1[i-1] + protein_1
        protein_2 = protein2[j-1] + protein_2
        i -= 1
        j -= 1
        
        if arah[1][i] =='/':
            protein_1 = protein1[0] + protein_1
            protein_2 = '-' + protein_2

    elif arah[j][i] == '-':
        i=i-1
        protein_1 = protein1[i-1] + protein_1
        protein_2 = '-' + protein_2

        
    elif arah[j][i] == '|':
        protein_1 = '-' + protein_1
        protein_2 = protein2[j-1] + protein_2
        j=j-1

    else:break
      


# Hasil Alignment

In [121]:
protein_1

'MNAL--QM'

In [122]:
protein_2

'-NALMSQA'